const fs = require('fs')

const displayNames = {
    "Bounce": "Bounce",
    "BowTieHorizontal": "Bow Tie Horizontal",
    "BowTieVertical": "Bow Tie Vertical",
    "BowTieWithParameter": "Bow Tie With Parameter",
    "ButterflyWaveScrawler": "Butterfly Wave Scrawler",
    "CircleCrop": "Circle Crop",
    "ColourDistance": "Colour Distance",
    "CrazyParametricFun": "Crazy ParametricFun",
    "CrossZoom": "Cross Zoom",
    "Directional": "Directional",
    "DoomScreenTransition": "Doom Screen",
    "Dreamy": "Dreamy",
    "DreamyZoom": "Dreamy Zoom",
    "FilmBurn": "Film Burn",
    "GlitchDisplace": "Glitch Displace",
    "GlitchMemories": "Glitch Memories",
    "GridFlip": "Grid Flip",
    "InvertedPageCurl": "Inverted Page Curl",
    "LeftRight": "Left Right",
    "LinearBlur": "Linear Blur",
    "Mosaic": "Mosaic",
    "PolkaDotsCurtain": "Polka Dots Curtain",
    "Radial": "Radial",
    "SimpleZoom": "Simple Zoom",
    "StereoViewer": "Stereo Viewer",
    "Swirl": "Swirl",
    "TVStatic": "TV Static",
    "TopBottom": "Top Bottom",
    "WaterDrop": "Water Drop",
    "ZoomInCircles": "Zoom In Circles",
    "angular": "Angular",
    "burn": "Burn",
    "cannabisleaf": "Leaf",
    "circle": "Circle",
    "circleopen": "Circle Open",
    "colorphase": "Color Phase",
    "crosshatch": "Cross Hatch",
    "crosswarp": "Cross Warp",
    "cube": "Cube",
    "directional-easing": "Directional",
    "directionalwarp": "Directional Warp",
    "directionalwipe": "Directional Wipe",
    "displacement": "Displacement",
    "doorway": "Doorway",
    "fade": "Fade",
    "fadecolor": "Fade Color",
    "fadegrayscale": "Fade Grayscale",
    "flyeye": "Flyeye",
    "heart": "Heart",
    "hexagonalize": "Hexagonalize",
    "kaleidoscope": "Kaleidoscope",
    "luma": "Luma",
    "luminance_melt": "Luminance Melt",
    "morph": "Morph",
    "multiply_blend": "Multiply Blend",
    "perlin": "Perlin",
    "pinwheel": "Pinwheel",
    "pixelize": "Pixelize",
    "polar_function": "Polar Function",
    "randomNoisex": "Random Noise X",
    "randomsquares": "Random Squares",
    "ripple": "Ripple",
    "rotateTransition": "Rotate",
    "rotate_scale_fade": "Rotate Scale Fade",
    "squareswire": "Squares Wire",
    "squeeze": "Squeeze",
    "swap": "Swap",
    "tangentMotionBlur": "Tangent Motion Blur",
    "undulatingBurnOut": "Undulating Burn Out",
    "wind": "Wind",
    "windowblinds": "Window Blinds",
    "windowslice": "Window Slice",
    "wipeDown": "Wipe Down",
    "wipeLeft": "Wipe Left",
    "wipeRight": "Wipe Right",
    "wipeUp": "Wipe Up",
}

const transitions = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'))
fs.writeFileSync(process.argv[2], JSON.stringify(transitions.map(transition => ({displayName: displayNames[transition.name], ...transition}))))